`define	DATA_WIDTH					10
`define	SHIFT_RF_2D_COL			18
`define	SHIFT_RF_2D_ROW			16

`define	SHIFT_RF_2D_ROW_SIZE		`SHIFT_RF_2D_COL * `DATA_WIDTH
`define	SHIFT_RF_2D_ROW_WORD		[`SHIFT_RF_2D_ROW_SIZE-1:0]